I added hover and transition effects to the memory-card image container…
GeraAlcantara/cards-memory-game pull request #30
Opened 2022-10-02 11:57 UTC by JosephOkpala

…, kindly merge my branch. Thank you

2022-10-02 23:48 UTC, GeraAlcantara requested changes

2022-10-02 23:48 UTC, GeraAlcantara commented on gameBase/src/css/styles.css
> +.memory-card img:hover {
nice effect just can you adapted so only when the card is not flip have that hover effect, hint on the class flip remove the hover effect

2022-10-03 00:15 UTC, JosephOkpala commented
Alright, I'm on it !


On Mon, 3 Oct 2022 at 00:48, Gerardo Alcantara ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In gameBase/src/css/styles.css
> <https://github.com/GeraAlcantara/cards-memory-game/pull/30#discussion_r985314990>
> :
>
> > @@ -30,6 +30,14 @@ body {
>    transition: transform 0.5s;
>  }
>
> +.memory-card img:hover {
>
> nice effect just can you adapted so only when the card is not flip have
> that hover effect, hint on the class flip remove the hover effect
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/GeraAlcantara/cards-memory-game/pull/30#pullrequestreview-1127710066>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZCIBBC7AN2XBHUHLMUZCJLWBINL3ANCNFSM6AAAAAAQ236GXY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-10-03 00:28 UTC, GeraAlcantara approved these changes

2022-10-03 00:30 UTC, merged

2022-10-03 00:31 UTC, JosephOkpala commented
I'm available for further tasks!

On Mon, 3 Oct 2022 at 01:30, Gerardo Alcantara ***@***.***>
wrote:

> Merged #30 <https://github.com/GeraAlcantara/cards-memory-game/pull/30>
> into main.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/GeraAlcantara/cards-memory-game/pull/30#event-7502835765>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZCIBBA2BR6VVTAX4YKATU3WBISJ5ANCNFSM6AAAAAAQ236GXY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> com>
>

2022-10-03 00:31 UTC, JosephOkpala commented
Thank You.


On Mon, 3 Oct 2022 at 01:31, Joseph Okpala ***@***.***>
wrote:

> I'm available for further tasks!
>
> On Mon, 3 Oct 2022 at 01:30, Gerardo Alcantara ***@***.***>
> wrote:
>
>> Merged #30 <https://github.com/GeraAlcantara/cards-memory-game/pull/30>
>> into main.
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/GeraAlcantara/cards-memory-game/pull/30#event-7502835765>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AZCIBBA2BR6VVTAX4YKATU3WBISJ5ANCNFSM6AAAAAAQ236GXY>
>> .
>> You are receiving this because you authored the thread.Message ID:
>> ***@***.***
>> com>
>>
>