Game Base Fix hover effect
GeraAlcantara/cards-memory-game pull request #56
Opened 2022-10-03 19:37 UTC by AaryanSingh0017

2022-10-03 22:50 UTC, GeraAlcantara requested changes

2022-10-03 22:50 UTC, GeraAlcantara commented on gameBase/src/css/Hover.css
> +@media (hover: hover) and (pointer: fine) {
you just need the query to @media (hover: hover) remove the and (pointer;fine) part 
and apply this concept to the style css file I'll tri to point the line where you need to aplly the change

2022-10-03 22:50 UTC, GeraAlcantara commented on gameBase/src/css/Hover.css
> +@media (hover: hover) and (pointer: fine) {
gameBase/src/css/styles.css
line 39 
apply the media query rule there

2022-10-03 22:50 UTC, GeraAlcantara commented on gameBase/src/css/Hover.css
> +@media (hover: hover) and (pointer: fine) {
and delete this file

2022-10-04 04:16 UTC, GeraAlcantara commented
issue was fix on PR #61

2022-10-04 04:16 UTC, closed without merging

2022-10-04 07:32 UTC, AaryanSingh0017 commented
okk

2022-10-04 07:54 UTC, AaryanSingh0017 commented
Plz remove the invalid tag its showing in Hacktoberfest, i Just made a minor mistake , I am new to open source and you can assign new task to me.